#!/usr/bin/env python3
# Offline per-customer key signer for db9pro v1.5.
# Reads MASTER_ROOT (32B) generated by db9_keygen.py, builds a 64-byte
# /media/fat/db9pro.key file with a customer-specific payload + SipHash-2-4
# MAC, and writes it to disk.
#
# Usage:
#   db9_sign.py \
#       --root ~/.db9pro-master/master_root.bin \
#       --customer-id 12345678 \
#       --features saturn \
#       --validity-days 90 \
#       --out ./12345678.db9pro.key
#
# Run on the same air-gapped machine as db9_keygen.py. The MASTER_ROOT
# never leaves that machine; only the resulting 64B key file is shipped to
# the customer.
#
# File layout (64 bytes, little-endian):
#   [ 0.. 3]  magic              "DB9K"  (0x4B394244 LE)
#   [ 4.. 5]  version            u16 = 0x0001
#   [ 6.. 7]  flags              u16 (bit0=test/dev key)
#   [ 8..15]  customer_id        u64 (non-zero)
#   [16..19]  issue_unix         u32
#   [20..23]  expiry_unix        u32
#   [24..27]  feature_mask       u32 (bit0=Saturn, bits 1..31 reserved)
#   [28..31]  reserved=0         u32
#   ----- signed range = bytes [0..32) -----
#   [32..39]  per_customer_seed  SipHash(MASTER_ROOT[:16], customer_id_8B_LE)
#                                (informational; v1.5 doesn't use it on FPGA,
#                                 reserved for v2 nonce-mode forward-compat)
#   [40..47]  auth_tag           SipHash(MASTER_ROOT[:16], bytes[0..32])
#   [48..63]  pad                zero-filled

import argparse
import json
import os
import struct
import sys
import time
from pathlib import Path


# ---- Pure-Python SipHash-2-4 (Aumasson + Bernstein, 2012) ----

_MASK64 = (1 << 64) - 1


def _rotl(x: int, b: int) -> int:
    return ((x << b) | (x >> (64 - b))) & _MASK64


def _siphash_round(v0: int, v1: int, v2: int, v3: int):
    v0 = (v0 + v1) & _MASK64
    v1 = _rotl(v1, 13) ^ v0
    v0 = _rotl(v0, 32)
    v2 = (v2 + v3) & _MASK64
    v3 = _rotl(v3, 16) ^ v2
    v0 = (v0 + v3) & _MASK64
    v3 = _rotl(v3, 21) ^ v0
    v2 = (v2 + v1) & _MASK64
    v1 = _rotl(v1, 17) ^ v2
    v2 = _rotl(v2, 32)
    return v0, v1, v2, v3


def siphash24(msg: bytes, key: bytes) -> bytes:
    """SipHash-2-4. key=16 bytes (k0=key[:8], k1=key[8:]). Returns 8 bytes LE."""
    if len(key) != 16:
        raise ValueError(f"key must be 16 bytes, got {len(key)}")

    k0 = int.from_bytes(key[:8],  "little")
    k1 = int.from_bytes(key[8:], "little")

    v0 = k0 ^ 0x736f6d6570736575
    v1 = k1 ^ 0x646f72616e646f6d
    v2 = k0 ^ 0x6c7967656e657261
    v3 = k1 ^ 0x7465646279746573

    end = len(msg) - (len(msg) & 7)
    for i in range(0, end, 8):
        m = int.from_bytes(msg[i:i + 8], "little")
        v3 ^= m
        v0, v1, v2, v3 = _siphash_round(v0, v1, v2, v3)
        v0, v1, v2, v3 = _siphash_round(v0, v1, v2, v3)
        v0 ^= m

    last = msg[end:]
    b = (len(msg) & 0xFF) << 56
    for i, byte in enumerate(last):
        b |= byte << (i * 8)

    v3 ^= b
    v0, v1, v2, v3 = _siphash_round(v0, v1, v2, v3)
    v0, v1, v2, v3 = _siphash_round(v0, v1, v2, v3)
    v0 ^= b

    v2 ^= 0xff
    for _ in range(4):
        v0, v1, v2, v3 = _siphash_round(v0, v1, v2, v3)

    return (v0 ^ v1 ^ v2 ^ v3).to_bytes(8, "little")


def _self_test():
    """Aumasson reference test vectors (key = 00 01 02 ... 0f).
    Tags expected as little-endian byte sequences."""
    key = bytes(range(16))
    cases = [
        # (msg, expected tag as hex of LE bytes)
        # u64 0x726fdb47dd0e0e31 -> LE bytes 31 0e 0e dd 47 db 6f 72
        (b"",                 "310e0edd47db6f72"),
        # u64 0x74f839c593dc67fd -> LE bytes fd 67 dc 93 c5 39 f8 74
        (bytes(range(0,  1)), "fd67dc93c539f874"),
        # u64 0xa129ca6149be45e5 -> LE bytes e5 45 be 49 61 ca 29 a1
        (bytes(range(0, 15)), "e545be4961ca29a1"),
    ]
    for msg, expected in cases:
        got = siphash24(msg, key).hex()
        if got != expected:
            sys.exit(f"siphash24 self-test FAILED: msg_len={len(msg)} got={got} want={expected}")


_self_test()


# ---- Key file builder ----

DB9_KEY_MAGIC   = 0x4B394244  # "DB9K" little-endian
DB9_KEY_VERSION = 0x0001
KEY_SIZE        = 64
SIGNED_RANGE    = 32

FEATURE_BITS = {
    "saturn": 0x00000001,
}

FLAG_TEST = 0x0001


def parse_features(s: str) -> int:
    if not s:
        return 0
    mask = 0
    for tok in s.split(","):
        tok = tok.strip().lower()
        if not tok:
            continue
        if tok not in FEATURE_BITS:
            sys.exit(f"unknown feature '{tok}' (allowed: {','.join(sorted(FEATURE_BITS))})")
        mask |= FEATURE_BITS[tok]
    return mask


def build_key(root: bytes, customer_id: int, feature_mask: int,
              validity_days: int, flags: int = 0,
              issue_unix: int | None = None) -> bytes:
    if len(root) != 32:
        raise ValueError(f"MASTER_ROOT must be 32 bytes, got {len(root)}")
    if not (0 < customer_id < 2**64):
        raise ValueError("customer_id must be 1..2^64-1")
    if validity_days <= 0:
        raise ValueError("validity_days must be positive")

    if issue_unix is None:
        issue_unix = int(time.time())
    expiry_unix = issue_unix + validity_days * 86400
    if expiry_unix > 0xFFFFFFFF:
        raise ValueError("expiry_unix overflows u32 (Y2106)")

    # Signed payload (32 bytes).
    payload = struct.pack(
        "<IHHQIIII",
        DB9_KEY_MAGIC, DB9_KEY_VERSION, flags,
        customer_id,
        issue_unix, expiry_unix, feature_mask,
        0,  # reserved
    )
    assert len(payload) == SIGNED_RANGE

    # MASTER_ROOT[:16] is the SipHash key (the high 16 bytes are reserved for
    # potential future split-key schemes; v1.5 uses only the low 16 bytes).
    sip_key = root[:16]

    # Per-customer seed: forward-compat with v2 (nonce mode would HMAC the
    # nonce with this seed). v1.5 ships it as opaque informational data.
    per_customer_seed = siphash24(customer_id.to_bytes(8, "little"), sip_key)

    auth_tag = siphash24(payload, sip_key)

    pad = bytes(16)

    blob = payload + per_customer_seed + auth_tag + pad
    assert len(blob) == KEY_SIZE
    return blob


def main() -> int:
    ap = argparse.ArgumentParser(
        description="db9pro v1.5 per-customer key signer (offline only).",
    )
    ap.add_argument("--root", required=True, type=Path,
                    help="MASTER_ROOT file (32B raw, from db9_keygen.py)")
    ap.add_argument("--customer-id", required=True, type=int, dest="customer_id",
                    help="customer ID (u64, non-zero)")
    ap.add_argument("--features", default="saturn",
                    help=f"comma-separated feature list "
                         f"(default 'saturn'). Allowed: {','.join(sorted(FEATURE_BITS))}")
    ap.add_argument("--validity-days", type=int, default=90, dest="validity_days",
                    help="days from now until expiry (default 90)")
    ap.add_argument("--test", action="store_true",
                    help="set test/dev flag (bit0); not for production keys")
    ap.add_argument("--issue-unix", type=int, default=None, dest="issue_unix",
                    help="override issue timestamp (default: now)")
    ap.add_argument("--out", required=True, type=Path,
                    help="output key file path")
    ap.add_argument("--force", action="store_true",
                    help="overwrite existing output file")
    args = ap.parse_args()

    if args.out.exists() and not args.force:
        sys.exit(f"{args.out} exists. Use --force to overwrite.")

    root = args.root.expanduser().read_bytes()
    if len(root) != 32:
        sys.exit(f"{args.root}: must be 32 bytes (got {len(root)})")

    feature_mask = parse_features(args.features)
    if feature_mask == 0:
        sys.exit("no features selected — key would be useless")

    flags = FLAG_TEST if args.test else 0

    blob = build_key(
        root=root,
        customer_id=args.customer_id,
        feature_mask=feature_mask,
        validity_days=args.validity_days,
        flags=flags,
        issue_unix=args.issue_unix,
    )

    args.out.write_bytes(blob)
    os.chmod(args.out, 0o644)

    issue  = args.issue_unix if args.issue_unix is not None else int(time.time())
    expiry = issue + args.validity_days * 86400

    print(f"Wrote {len(blob)} bytes to {args.out}")
    print(f"  customer_id   : {args.customer_id}")
    print(f"  issue_unix    : {issue}  ({time.strftime('%Y-%m-%d', time.gmtime(issue))} UTC)")
    print(f"  expiry_unix   : {expiry} ({time.strftime('%Y-%m-%d', time.gmtime(expiry))} UTC)")
    print(f"  features      : 0x{feature_mask:08x}  ({args.features})")
    print(f"  flags         : 0x{flags:04x}")
    print(f"  auth_tag      : {blob[40:48].hex()}")
    print()
    print("Audit log line (append to ~/.db9pro-master/audit.jsonl):")
    log = {
        "ts":          int(time.time()),
        "customer_id": args.customer_id,
        "issue":       issue,
        "expiry":      expiry,
        "features":    feature_mask,
        "flags":       flags,
        "out":         str(args.out),
        "tag_prefix":  blob[40:48].hex(),
    }
    print(json.dumps(log))
    return 0


if __name__ == "__main__":
    sys.exit(main())
