name: Push Release

on:
  push:
    branches:
      - <<MAIN_BRANCH>>
  repository_dispatch:
    types: [push_release]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Docker image
      uses: actions/cache@v4
      with:
        path: /tmp/docker-image.tar
        key: docker-<<QUARTUS_IMAGE>>

    - name: Load or pull Docker image
      run: |
        if [ -f /tmp/docker-image.tar ]; then
          docker load -i /tmp/docker-image.tar
        else
          docker pull "<<QUARTUS_IMAGE>>"
          docker save "<<QUARTUS_IMAGE>>" -o /tmp/docker-image.tar
        fi

    - name: Release
      run: ./.github/push_release.sh <<MAINTAINER_EMAILS>>
      env:
        NOTIFICATION_API_KEY: ${{ secrets.NOTIFICATION_API_KEY }}
        FORCED: ${{ github.event.client_payload.forced }}
