name: Sync + Release

on:
  repository_dispatch:
    types: [sync_release]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Sync with upstream + Release
      run: ./.github/sync_release.sh <<MAINTAINER_EMAILS>>
      env:
        NOTIFICATION_API_KEY: ${{ secrets.NOTIFICATION_API_KEY }}
