name: Sync + Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  repository_dispatch:
    types: [sync_release]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: false   # this is too slow, just skip
        docker-images: true
        swap-storage: true

    - uses: actions/checkout@v6

    - name: Cache Docker image
      uses: actions/cache@v5
      with:
        path: /tmp/docker-image.tar
        key: docker-<<QUARTUS_IMAGE>>

    - name: Sync with upstream + Release
      run: ./.github/sync_release.sh <<MAINTAINER_EMAILS>>
      env:
        NOTIFICATION_API_KEY: ${{ secrets.NOTIFICATION_API_KEY }}
