ARG QUARTUS_IMAGE
FROM ${QUARTUS_IMAGE}
LABEL maintainer="theypsilon@gmail.com"
ARG COMPILATION_INPUT
ARG COMPILATION_OUTPUT
ENV COMPILATION_OUTPUT=${COMPILATION_OUTPUT}
WORKDIR /project
ADD . /project
RUN /opt/intelFPGA_lite/quartus/bin/quartus_sh --flow compile ${COMPILATION_INPUT}
CMD cat /project/${COMPILATION_OUTPUT}
