name: Setup CI/CD

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [setup_cicd]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup CI/CD on Forks
      run: ./.github/setup_cicd.sh
      env:
        DISPATCH_USER: theypsilon
        DISPATCH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_THEYPSILON }}
        PARALLEL_JOBS: 16
