name: Setup CI/CD

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [setup_cicd]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup CI/CD on Forks
      run: ./.github/setup_cicd.sh
      env:
        DISPATCH_USER: theypsilon
        DISPATCH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_THEYPSILON }}
