name: Sync Forks

on:
  schedule:
    - cron:  '0 18 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [sync_forks]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Sync Forks
      run: ./.github/sync_forks.sh
      env:
        DISPATCH_USER: theypsilon
        DISPATCH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_THEYPSILON }}
