name: Sync Forks

on:
  schedule:
    - cron:  '0 18 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [sync_forks]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Sync Forks
      run: ./.github/sync_forks.sh
      env:
        DISPATCH_USER: x-access-token
        DISPATCH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
        PARALLEL_JOBS: 16
