name: Sync Forks

on:
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Sync Forks
      run: ./.github/sync_forks.sh
      env:
        DISPATCH_USER: theypsilon
        DISPATCH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_THEYPSILON }}
