name: Sync Forks

on:
  schedule:
    - cron:  '0 18 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [sync_forks]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Sync Forks
      run: ./.github/sync_forks.sh
      env:
        DISPATCH_USER: x-access-token
        DISPATCH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
        PARALLEL_JOBS: 16
